package hu.javauniversity.myapp2023.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import hu.javauniversity.myapp2023.DAL.UserRepository;
import hu.javauniversity.myapp2023.model.User;

// this class is a Controller
@Controller
// url's start with /'something' (after application path)
@RequestMapping(path="/myapp2023demo")
public class MainController {

    // it means to get the bean called userRepository which is auto-generated by Spring (we use it to handle the data)
    @Autowired
    private UserRepository userRepository;

    // map only POST requests
    @PostMapping(path="/add")
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email, @RequestParam String phone) {
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        user.setPhone(phone);
        userRepository.save(user);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // it returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
